
include: package:flutter_lints/flutter.yaml

linter:
 
  rules:
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: false
    prefer_const_constructors_in_immutables: false
    constant_identifier_names: false