name: gestao_escala
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: #^4.3.8
    git: https://github.com/jonataslaw/getx.git
  google_fonts: ^3.0.1
  animated_card: ^2.0.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  google_sign_in: ^5.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo-app.png
    - assets/images/google.png

 
